import Head from 'next/head';
import { PostCard, Categories, PostWidget } from '../components/index';
import { getPosts } from '../services';
import { FeaturedPosts } from '../sections/index';

export default function Home({ posts }) {

	return (
		<div className='container mx-auto px-10 mb-8'>
			<Head>
				<title>Dev Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<FeaturedPosts />
			<div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
				<div className='lg:col-span-8 col-span-1'>
					{posts.map((post, index) => (<PostCard post={post.node} key={index} />))}
				</div>

				<div className='lg:col-span-4 col-span-1'>
					<div className="lg:sticky relative top-8">
						<PostWidget />
						<Categories />
					</div>
				</div>
			</div>
		</div>
	)
}

// Feth data con getStaticProps y NextJS
export async function getStaticProps(){
	const posts = (await getPosts()) || [];

	return {
		props: { posts }
	}
}

// export async function getStaticProps(){

// 	const client = new ApolloClient({
// 		uri: 'http://localhost:1337/graphql',
// 		cache: new InMemoryCache()
// 	});

// 	const { data } = await client.query({
// 		query: gql`
// 		{
// 			posts {
// 			  author {
// 				 bio
// 				 name
// 				 id
// 				 photo{
// 					url
// 				 }
// 			  }
// 			  createdAt
// 			  slug
// 			  title
// 			  excerpt
// 			  featuredImage{
// 				 url
// 			  }
// 			  categories {
// 				 name
// 				 slug
// 			  }
// 			}
// 		 }
// 		`
// 	})

// 	return {
// 		props: {
// 			posts: data.posts
// 		}
// 	}
// }